# => https://starship.rs/config/

format = """
$time\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$java\
$docker_context\
$python\
$ruby\
$memory_usage\
$status\
$character\
"""

[character]
[cmd_duration]

[directory]
style="blue"
read_only="ï€£"
truncation_symbol="ï "
truncation_length=-1

[git_branch]
style="purple"
symbol = "ï˜ "

[time]
disabled = false
format = 'ğŸ•™ [\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "local"
time_range = "-"

[git_state]
[git_status]
[line_break]
[status]

[docker_context]
symbol = "ïŒˆ "

[java]
symbol = "î‰– "

[memory_usage]
symbol = "ï¡š "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

############################################################################false
# NOT USED:

[aws]
disabled = true

[battery]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]

[erlang]
disabled = true

[gcloud]
disabled = true

[golang]
disable = true

[helm]
disable = true

[hostname]
disable = true

[jobs]
disable = true

[julia]
disable = true

[kubernetes]
disable = true

[lua]
disable = true

[hg_branch]
disable = true

[nim]
disable = true

[nix_shell]
disable = true

[nodejs]
disable = true

[ocaml]
disable = true

[openstack]
disable = true

[package]
disable = true

[perl]
disable = true

[php]
disable = true

[purescript]
disable = true

[rust]
disable = true

[shlvl]
disable = true

[singularity]
disable = true

[swift]
disable = true

[terraform]
disable = true

[username]
disable = true

[zig]
disable = true
